### PR TITLE
add use cases in DeveloperGuide.adoc and renamed Yingnan's photo

### PR DESCRIPTION
**Pull request by NancyQuris**

### CODE REVIEW

**Comment by hidingmode** [comment]
Initially I thought to group them up more, that's why I got the [1 for many] section in the gdoc, but if you think this is better, then I'm ok with this too.

Please reorder them so that it follows the order of the command summary.

**Comment by NancyQuris** [comment]
I am simply following what we have come up with in the gdoc. I will update later.

**Comment by hidingmode** [comment]
Yingnan's part for #3

**Comment by NancyQuris** [comment]
I will update the command later in this week.

**Pull request merged**
